---
- name: Configure nginx web server
  hosts: webserver
  become: yes
  tasks:
  - name: Install nginx server
    apt:
      name: nginx
      state: latest
  - name: Start nginx server
    service:
      name: nginx
      state: started